from .about import AboutView
from .confirmation import ConfirmView
from .delete_task import DeleteTaskView
from .edit_profile import EditProfileView
from .home import HomeView
from .login import LoginView
from .logout import LogoutView
from .new_task import NewTaskView
from .staff_main import StaffMainView
from .task import TaskView
from .user_profile import UserProfileView
from .user_reg import RegistrationView
from .staff_reg import StaffRegistrationView
from .fast_task import FastTaskView
