# Generated by Django 4.2 on 2023-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_task_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="end_work",
        ),
        migrations.AlterField(
            model_name="staff",
            name="percent",
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="salary",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
