# Generated by Django 4.2 on 2023-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_category_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Анонімний користувач", max_length=200),
                ),
                ("phone", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(default="Проблема не вказана", max_length=1000),
                ),
            ],
            options={
                "verbose_name": "Зворотній дзвінок",
                "verbose_name_plural": "Зворотні дзвінки",
            },
        ),
    ]
