# Generated by Django 4.2 on 2023-05-09 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_callback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callback",
            name="description",
        ),
    ]
