# Generated by Django 4.2 on 2023-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_customer_username_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(default="Default", max_length=200),
        ),
    ]
