# Generated by Django 4.2 on 2023-05-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_customer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
