# Generated by Django 4.2 on 2023-05-09 21:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
