# Generated by Django 4.2 on 2023-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_customer_managers_alter_staff_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user_name",
            field=models.CharField(default="Анонім", max_length=200, null=True),
        ),
    ]
